require: rubocop-rspec

AllCops:
  TargetRubyVersion: 2.5+
  Exclude:
    - ./*.gemspec

Metrics/BlockLength:
  ExcludedMethods: ['context', 'describe']

Metrics/LineLength:
  Max: 100

RSpec/BeforeAfterAll:
  Enabled: false

Style/BlockDelimiters:
  EnforcedStyle: braces_for_chaining

Style/FrozenStringLiteralComment:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes
